// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/surfstore/SurfStore.proto

package surfstore

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BlockHash struct {
	Hash                 string   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockHash) Reset()         { *m = BlockHash{} }
func (m *BlockHash) String() string { return proto.CompactTextString(m) }
func (*BlockHash) ProtoMessage()    {}
func (*BlockHash) Descriptor() ([]byte, []int) {
	return fileDescriptor_74dffadc931fead4, []int{0}
}

func (m *BlockHash) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockHash.Unmarshal(m, b)
}
func (m *BlockHash) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockHash.Marshal(b, m, deterministic)
}
func (m *BlockHash) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockHash.Merge(m, src)
}
func (m *BlockHash) XXX_Size() int {
	return xxx_messageInfo_BlockHash.Size(m)
}
func (m *BlockHash) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockHash.DiscardUnknown(m)
}

var xxx_messageInfo_BlockHash proto.InternalMessageInfo

func (m *BlockHash) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

type BlockHashes struct {
	Hashes               []string `protobuf:"bytes,1,rep,name=hashes,proto3" json:"hashes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockHashes) Reset()         { *m = BlockHashes{} }
func (m *BlockHashes) String() string { return proto.CompactTextString(m) }
func (*BlockHashes) ProtoMessage()    {}
func (*BlockHashes) Descriptor() ([]byte, []int) {
	return fileDescriptor_74dffadc931fead4, []int{1}
}

func (m *BlockHashes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockHashes.Unmarshal(m, b)
}
func (m *BlockHashes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockHashes.Marshal(b, m, deterministic)
}
func (m *BlockHashes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockHashes.Merge(m, src)
}
func (m *BlockHashes) XXX_Size() int {
	return xxx_messageInfo_BlockHashes.Size(m)
}
func (m *BlockHashes) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockHashes.DiscardUnknown(m)
}

var xxx_messageInfo_BlockHashes proto.InternalMessageInfo

func (m *BlockHashes) GetHashes() []string {
	if m != nil {
		return m.Hashes
	}
	return nil
}

type Block struct {
	BlockData            []byte   `protobuf:"bytes,1,opt,name=blockData,proto3" json:"blockData,omitempty"`
	BlockSize            int32    `protobuf:"varint,2,opt,name=blockSize,proto3" json:"blockSize,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Block) Reset()         { *m = Block{} }
func (m *Block) String() string { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()    {}
func (*Block) Descriptor() ([]byte, []int) {
	return fileDescriptor_74dffadc931fead4, []int{2}
}

func (m *Block) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block.Unmarshal(m, b)
}
func (m *Block) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block.Marshal(b, m, deterministic)
}
func (m *Block) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block.Merge(m, src)
}
func (m *Block) XXX_Size() int {
	return xxx_messageInfo_Block.Size(m)
}
func (m *Block) XXX_DiscardUnknown() {
	xxx_messageInfo_Block.DiscardUnknown(m)
}

var xxx_messageInfo_Block proto.InternalMessageInfo

func (m *Block) GetBlockData() []byte {
	if m != nil {
		return m.BlockData
	}
	return nil
}

func (m *Block) GetBlockSize() int32 {
	if m != nil {
		return m.BlockSize
	}
	return 0
}

type Success struct {
	Flag                 bool     `protobuf:"varint,1,opt,name=flag,proto3" json:"flag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Success) Reset()         { *m = Success{} }
func (m *Success) String() string { return proto.CompactTextString(m) }
func (*Success) ProtoMessage()    {}
func (*Success) Descriptor() ([]byte, []int) {
	return fileDescriptor_74dffadc931fead4, []int{3}
}

func (m *Success) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Success.Unmarshal(m, b)
}
func (m *Success) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Success.Marshal(b, m, deterministic)
}
func (m *Success) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Success.Merge(m, src)
}
func (m *Success) XXX_Size() int {
	return xxx_messageInfo_Success.Size(m)
}
func (m *Success) XXX_DiscardUnknown() {
	xxx_messageInfo_Success.DiscardUnknown(m)
}

var xxx_messageInfo_Success proto.InternalMessageInfo

func (m *Success) GetFlag() bool {
	if m != nil {
		return m.Flag
	}
	return false
}

type FileMetaData struct {
	Filename             string   `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Version              int32    `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	BlockHashList        []string `protobuf:"bytes,3,rep,name=blockHashList,proto3" json:"blockHashList,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileMetaData) Reset()         { *m = FileMetaData{} }
func (m *FileMetaData) String() string { return proto.CompactTextString(m) }
func (*FileMetaData) ProtoMessage()    {}
func (*FileMetaData) Descriptor() ([]byte, []int) {
	return fileDescriptor_74dffadc931fead4, []int{4}
}

func (m *FileMetaData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileMetaData.Unmarshal(m, b)
}
func (m *FileMetaData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileMetaData.Marshal(b, m, deterministic)
}
func (m *FileMetaData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileMetaData.Merge(m, src)
}
func (m *FileMetaData) XXX_Size() int {
	return xxx_messageInfo_FileMetaData.Size(m)
}
func (m *FileMetaData) XXX_DiscardUnknown() {
	xxx_messageInfo_FileMetaData.DiscardUnknown(m)
}

var xxx_messageInfo_FileMetaData proto.InternalMessageInfo

func (m *FileMetaData) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *FileMetaData) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *FileMetaData) GetBlockHashList() []string {
	if m != nil {
		return m.BlockHashList
	}
	return nil
}

type FileInfoMap struct {
	FileInfoMap          map[string]*FileMetaData `protobuf:"bytes,1,rep,name=fileInfoMap,proto3" json:"fileInfoMap,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *FileInfoMap) Reset()         { *m = FileInfoMap{} }
func (m *FileInfoMap) String() string { return proto.CompactTextString(m) }
func (*FileInfoMap) ProtoMessage()    {}
func (*FileInfoMap) Descriptor() ([]byte, []int) {
	return fileDescriptor_74dffadc931fead4, []int{5}
}

func (m *FileInfoMap) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileInfoMap.Unmarshal(m, b)
}
func (m *FileInfoMap) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileInfoMap.Marshal(b, m, deterministic)
}
func (m *FileInfoMap) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileInfoMap.Merge(m, src)
}
func (m *FileInfoMap) XXX_Size() int {
	return xxx_messageInfo_FileInfoMap.Size(m)
}
func (m *FileInfoMap) XXX_DiscardUnknown() {
	xxx_messageInfo_FileInfoMap.DiscardUnknown(m)
}

var xxx_messageInfo_FileInfoMap proto.InternalMessageInfo

func (m *FileInfoMap) GetFileInfoMap() map[string]*FileMetaData {
	if m != nil {
		return m.FileInfoMap
	}
	return nil
}

type Version struct {
	Version              int32    `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Version) Reset()         { *m = Version{} }
func (m *Version) String() string { return proto.CompactTextString(m) }
func (*Version) ProtoMessage()    {}
func (*Version) Descriptor() ([]byte, []int) {
	return fileDescriptor_74dffadc931fead4, []int{6}
}

func (m *Version) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Version.Unmarshal(m, b)
}
func (m *Version) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Version.Marshal(b, m, deterministic)
}
func (m *Version) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Version.Merge(m, src)
}
func (m *Version) XXX_Size() int {
	return xxx_messageInfo_Version.Size(m)
}
func (m *Version) XXX_DiscardUnknown() {
	xxx_messageInfo_Version.DiscardUnknown(m)
}

var xxx_messageInfo_Version proto.InternalMessageInfo

func (m *Version) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

type BlockStoreMap struct {
	BlockStoreMap        map[string]*BlockHashes `protobuf:"bytes,1,rep,name=blockStoreMap,proto3" json:"blockStoreMap,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *BlockStoreMap) Reset()         { *m = BlockStoreMap{} }
func (m *BlockStoreMap) String() string { return proto.CompactTextString(m) }
func (*BlockStoreMap) ProtoMessage()    {}
func (*BlockStoreMap) Descriptor() ([]byte, []int) {
	return fileDescriptor_74dffadc931fead4, []int{7}
}

func (m *BlockStoreMap) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockStoreMap.Unmarshal(m, b)
}
func (m *BlockStoreMap) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockStoreMap.Marshal(b, m, deterministic)
}
func (m *BlockStoreMap) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockStoreMap.Merge(m, src)
}
func (m *BlockStoreMap) XXX_Size() int {
	return xxx_messageInfo_BlockStoreMap.Size(m)
}
func (m *BlockStoreMap) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockStoreMap.DiscardUnknown(m)
}

var xxx_messageInfo_BlockStoreMap proto.InternalMessageInfo

func (m *BlockStoreMap) GetBlockStoreMap() map[string]*BlockHashes {
	if m != nil {
		return m.BlockStoreMap
	}
	return nil
}

type BlockStoreAddrs struct {
	BlockStoreAddrs      []string `protobuf:"bytes,1,rep,name=blockStoreAddrs,proto3" json:"blockStoreAddrs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockStoreAddrs) Reset()         { *m = BlockStoreAddrs{} }
func (m *BlockStoreAddrs) String() string { return proto.CompactTextString(m) }
func (*BlockStoreAddrs) ProtoMessage()    {}
func (*BlockStoreAddrs) Descriptor() ([]byte, []int) {
	return fileDescriptor_74dffadc931fead4, []int{8}
}

func (m *BlockStoreAddrs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockStoreAddrs.Unmarshal(m, b)
}
func (m *BlockStoreAddrs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockStoreAddrs.Marshal(b, m, deterministic)
}
func (m *BlockStoreAddrs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockStoreAddrs.Merge(m, src)
}
func (m *BlockStoreAddrs) XXX_Size() int {
	return xxx_messageInfo_BlockStoreAddrs.Size(m)
}
func (m *BlockStoreAddrs) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockStoreAddrs.DiscardUnknown(m)
}

var xxx_messageInfo_BlockStoreAddrs proto.InternalMessageInfo

func (m *BlockStoreAddrs) GetBlockStoreAddrs() []string {
	if m != nil {
		return m.BlockStoreAddrs
	}
	return nil
}

type CrashedState struct {
	IsCrashed            bool     `protobuf:"varint,1,opt,name=isCrashed,proto3" json:"isCrashed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CrashedState) Reset()         { *m = CrashedState{} }
func (m *CrashedState) String() string { return proto.CompactTextString(m) }
func (*CrashedState) ProtoMessage()    {}
func (*CrashedState) Descriptor() ([]byte, []int) {
	return fileDescriptor_74dffadc931fead4, []int{9}
}

func (m *CrashedState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CrashedState.Unmarshal(m, b)
}
func (m *CrashedState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CrashedState.Marshal(b, m, deterministic)
}
func (m *CrashedState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CrashedState.Merge(m, src)
}
func (m *CrashedState) XXX_Size() int {
	return xxx_messageInfo_CrashedState.Size(m)
}
func (m *CrashedState) XXX_DiscardUnknown() {
	xxx_messageInfo_CrashedState.DiscardUnknown(m)
}

var xxx_messageInfo_CrashedState proto.InternalMessageInfo

func (m *CrashedState) GetIsCrashed() bool {
	if m != nil {
		return m.IsCrashed
	}
	return false
}

type AppendEntryInput struct {
	Term                 int64              `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	PrevLogIndex         int64              `protobuf:"varint,2,opt,name=prevLogIndex,proto3" json:"prevLogIndex,omitempty"`
	PrevLogTerm          int64              `protobuf:"varint,3,opt,name=prevLogTerm,proto3" json:"prevLogTerm,omitempty"`
	Entries              []*UpdateOperation `protobuf:"bytes,4,rep,name=entries,proto3" json:"entries,omitempty"`
	LeaderCommit         int64              `protobuf:"varint,5,opt,name=leaderCommit,proto3" json:"leaderCommit,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *AppendEntryInput) Reset()         { *m = AppendEntryInput{} }
func (m *AppendEntryInput) String() string { return proto.CompactTextString(m) }
func (*AppendEntryInput) ProtoMessage()    {}
func (*AppendEntryInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_74dffadc931fead4, []int{10}
}

func (m *AppendEntryInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppendEntryInput.Unmarshal(m, b)
}
func (m *AppendEntryInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppendEntryInput.Marshal(b, m, deterministic)
}
func (m *AppendEntryInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppendEntryInput.Merge(m, src)
}
func (m *AppendEntryInput) XXX_Size() int {
	return xxx_messageInfo_AppendEntryInput.Size(m)
}
func (m *AppendEntryInput) XXX_DiscardUnknown() {
	xxx_messageInfo_AppendEntryInput.DiscardUnknown(m)
}

var xxx_messageInfo_AppendEntryInput proto.InternalMessageInfo

func (m *AppendEntryInput) GetTerm() int64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *AppendEntryInput) GetPrevLogIndex() int64 {
	if m != nil {
		return m.PrevLogIndex
	}
	return 0
}

func (m *AppendEntryInput) GetPrevLogTerm() int64 {
	if m != nil {
		return m.PrevLogTerm
	}
	return 0
}

func (m *AppendEntryInput) GetEntries() []*UpdateOperation {
	if m != nil {
		return m.Entries
	}
	return nil
}

func (m *AppendEntryInput) GetLeaderCommit() int64 {
	if m != nil {
		return m.LeaderCommit
	}
	return 0
}

type AppendEntryOutput struct {
	ServerId             int64    `protobuf:"varint,1,opt,name=serverId,proto3" json:"serverId,omitempty"`
	Term                 int64    `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	Success              bool     `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	MatchedIndex         int64    `protobuf:"varint,4,opt,name=matchedIndex,proto3" json:"matchedIndex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppendEntryOutput) Reset()         { *m = AppendEntryOutput{} }
func (m *AppendEntryOutput) String() string { return proto.CompactTextString(m) }
func (*AppendEntryOutput) ProtoMessage()    {}
func (*AppendEntryOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_74dffadc931fead4, []int{11}
}

func (m *AppendEntryOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppendEntryOutput.Unmarshal(m, b)
}
func (m *AppendEntryOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppendEntryOutput.Marshal(b, m, deterministic)
}
func (m *AppendEntryOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppendEntryOutput.Merge(m, src)
}
func (m *AppendEntryOutput) XXX_Size() int {
	return xxx_messageInfo_AppendEntryOutput.Size(m)
}
func (m *AppendEntryOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_AppendEntryOutput.DiscardUnknown(m)
}

var xxx_messageInfo_AppendEntryOutput proto.InternalMessageInfo

func (m *AppendEntryOutput) GetServerId() int64 {
	if m != nil {
		return m.ServerId
	}
	return 0
}

func (m *AppendEntryOutput) GetTerm() int64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *AppendEntryOutput) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *AppendEntryOutput) GetMatchedIndex() int64 {
	if m != nil {
		return m.MatchedIndex
	}
	return 0
}

type UpdateOperation struct {
	Term                 int64         `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	FileMetaData         *FileMetaData `protobuf:"bytes,3,opt,name=fileMetaData,proto3" json:"fileMetaData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *UpdateOperation) Reset()         { *m = UpdateOperation{} }
func (m *UpdateOperation) String() string { return proto.CompactTextString(m) }
func (*UpdateOperation) ProtoMessage()    {}
func (*UpdateOperation) Descriptor() ([]byte, []int) {
	return fileDescriptor_74dffadc931fead4, []int{12}
}

func (m *UpdateOperation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateOperation.Unmarshal(m, b)
}
func (m *UpdateOperation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateOperation.Marshal(b, m, deterministic)
}
func (m *UpdateOperation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateOperation.Merge(m, src)
}
func (m *UpdateOperation) XXX_Size() int {
	return xxx_messageInfo_UpdateOperation.Size(m)
}
func (m *UpdateOperation) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateOperation.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateOperation proto.InternalMessageInfo

func (m *UpdateOperation) GetTerm() int64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *UpdateOperation) GetFileMetaData() *FileMetaData {
	if m != nil {
		return m.FileMetaData
	}
	return nil
}

type RaftInternalState struct {
	IsLeader             bool               `protobuf:"varint,1,opt,name=isLeader,proto3" json:"isLeader,omitempty"`
	Term                 int64              `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	Log                  []*UpdateOperation `protobuf:"bytes,3,rep,name=log,proto3" json:"log,omitempty"`
	MetaMap              *FileInfoMap       `protobuf:"bytes,4,opt,name=metaMap,proto3" json:"metaMap,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *RaftInternalState) Reset()         { *m = RaftInternalState{} }
func (m *RaftInternalState) String() string { return proto.CompactTextString(m) }
func (*RaftInternalState) ProtoMessage()    {}
func (*RaftInternalState) Descriptor() ([]byte, []int) {
	return fileDescriptor_74dffadc931fead4, []int{13}
}

func (m *RaftInternalState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RaftInternalState.Unmarshal(m, b)
}
func (m *RaftInternalState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RaftInternalState.Marshal(b, m, deterministic)
}
func (m *RaftInternalState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RaftInternalState.Merge(m, src)
}
func (m *RaftInternalState) XXX_Size() int {
	return xxx_messageInfo_RaftInternalState.Size(m)
}
func (m *RaftInternalState) XXX_DiscardUnknown() {
	xxx_messageInfo_RaftInternalState.DiscardUnknown(m)
}

var xxx_messageInfo_RaftInternalState proto.InternalMessageInfo

func (m *RaftInternalState) GetIsLeader() bool {
	if m != nil {
		return m.IsLeader
	}
	return false
}

func (m *RaftInternalState) GetTerm() int64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *RaftInternalState) GetLog() []*UpdateOperation {
	if m != nil {
		return m.Log
	}
	return nil
}

func (m *RaftInternalState) GetMetaMap() *FileInfoMap {
	if m != nil {
		return m.MetaMap
	}
	return nil
}

func init() {
	proto.RegisterType((*BlockHash)(nil), "surfstore.BlockHash")
	proto.RegisterType((*BlockHashes)(nil), "surfstore.BlockHashes")
	proto.RegisterType((*Block)(nil), "surfstore.Block")
	proto.RegisterType((*Success)(nil), "surfstore.Success")
	proto.RegisterType((*FileMetaData)(nil), "surfstore.FileMetaData")
	proto.RegisterType((*FileInfoMap)(nil), "surfstore.FileInfoMap")
	proto.RegisterMapType((map[string]*FileMetaData)(nil), "surfstore.FileInfoMap.FileInfoMapEntry")
	proto.RegisterType((*Version)(nil), "surfstore.Version")
	proto.RegisterType((*BlockStoreMap)(nil), "surfstore.BlockStoreMap")
	proto.RegisterMapType((map[string]*BlockHashes)(nil), "surfstore.BlockStoreMap.BlockStoreMapEntry")
	proto.RegisterType((*BlockStoreAddrs)(nil), "surfstore.BlockStoreAddrs")
	proto.RegisterType((*CrashedState)(nil), "surfstore.CrashedState")
	proto.RegisterType((*AppendEntryInput)(nil), "surfstore.AppendEntryInput")
	proto.RegisterType((*AppendEntryOutput)(nil), "surfstore.AppendEntryOutput")
	proto.RegisterType((*UpdateOperation)(nil), "surfstore.UpdateOperation")
	proto.RegisterType((*RaftInternalState)(nil), "surfstore.RaftInternalState")
}

func init() {
	proto.RegisterFile("pkg/surfstore/SurfStore.proto", fileDescriptor_74dffadc931fead4)
}

var fileDescriptor_74dffadc931fead4 = []byte{
	// 925 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x56, 0xcf, 0x6f, 0xe3, 0x44,
	0x14, 0x8e, 0x9b, 0x66, 0x93, 0xbc, 0x24, 0x34, 0x3b, 0x42, 0x8b, 0xe5, 0xed, 0x8a, 0x6a, 0x00,
	0x51, 0x89, 0x92, 0xa0, 0xd0, 0x15, 0x3f, 0x2a, 0x0e, 0xdb, 0xb2, 0x4b, 0xb3, 0xea, 0x6a, 0xc1,
	0xe1, 0x97, 0xb8, 0x4d, 0xe2, 0xe7, 0xc4, 0x5b, 0xc7, 0xb6, 0x3c, 0x93, 0x8a, 0x72, 0xe3, 0x3f,
	0x41, 0xe2, 0xc2, 0x95, 0x3b, 0x67, 0xfe, 0x27, 0x6e, 0x68, 0x66, 0x6c, 0x67, 0x9c, 0xc4, 0x2b,
	0x7a, 0xe7, 0x36, 0xef, 0xf9, 0x9b, 0x37, 0xef, 0x7b, 0xef, 0x9b, 0x37, 0x86, 0x47, 0xc9, 0xf5,
	0x7c, 0xc8, 0x57, 0xa9, 0xcf, 0x45, 0x9c, 0xe2, 0x70, 0xb2, 0x4a, 0xfd, 0x89, 0x5c, 0x0d, 0x92,
	0x34, 0x16, 0x31, 0x69, 0x17, 0x9f, 0x9c, 0x87, 0xf3, 0x38, 0x9e, 0x87, 0x38, 0x54, 0x1f, 0xa6,
	0x2b, 0x7f, 0x88, 0xcb, 0x44, 0xdc, 0x6a, 0x1c, 0x7d, 0x1b, 0xda, 0xe7, 0x61, 0x3c, 0xbb, 0xbe,
	0x64, 0x7c, 0x41, 0x08, 0xec, 0x2f, 0x18, 0x5f, 0xd8, 0xd6, 0x91, 0x75, 0xdc, 0x76, 0xd5, 0x9a,
	0xbe, 0x07, 0x9d, 0x02, 0x80, 0x9c, 0x3c, 0x80, 0x7b, 0x0b, 0xb5, 0xb2, 0xad, 0xa3, 0xfa, 0x71,
	0xdb, 0xcd, 0x2c, 0x7a, 0x01, 0x0d, 0x05, 0x23, 0x87, 0xd0, 0x9e, 0xca, 0xc5, 0x97, 0x4c, 0x30,
	0x15, 0xa8, 0xeb, 0xae, 0x1d, 0xc5, 0xd7, 0x49, 0xf0, 0x0b, 0xda, 0x7b, 0x47, 0xd6, 0x71, 0xc3,
	0x5d, 0x3b, 0xe8, 0x23, 0x68, 0x4e, 0x56, 0xb3, 0x19, 0x72, 0x2e, 0x53, 0xf1, 0x43, 0x36, 0x57,
	0x11, 0x5a, 0xae, 0x5a, 0xd3, 0x57, 0xd0, 0x7d, 0x16, 0x84, 0xf8, 0x02, 0x05, 0x53, 0xc1, 0x1c,
	0x68, 0xf9, 0x41, 0x88, 0x11, 0x5b, 0x62, 0x96, 0x72, 0x61, 0x13, 0x1b, 0x9a, 0x37, 0x98, 0xf2,
	0x20, 0x8e, 0xb2, 0x63, 0x72, 0x93, 0xbc, 0x0b, 0xbd, 0x69, 0x4e, 0xe8, 0x2a, 0xe0, 0xc2, 0xae,
	0x2b, 0x22, 0x65, 0x27, 0xfd, 0xd3, 0x82, 0x8e, 0x3c, 0x6c, 0x1c, 0xf9, 0xf1, 0x0b, 0x96, 0x90,
	0x31, 0x74, 0xfc, 0xb5, 0xa9, 0xc8, 0x77, 0x46, 0xef, 0x0f, 0x8a, 0x2a, 0x0f, 0x0c, 0xb0, 0xb9,
	0x7e, 0x1a, 0x89, 0xf4, 0xd6, 0x35, 0xf7, 0x3a, 0x3f, 0x40, 0x7f, 0x13, 0x40, 0xfa, 0x50, 0xbf,
	0xc6, 0xdb, 0x8c, 0x85, 0x5c, 0x92, 0x0f, 0xa1, 0x71, 0xc3, 0xc2, 0x95, 0xae, 0x52, 0x67, 0xf4,
	0xd6, 0xc6, 0x51, 0x79, 0x11, 0x5c, 0x8d, 0xfa, 0x7c, 0xef, 0x53, 0x8b, 0xbe, 0x03, 0xcd, 0xef,
	0x33, 0x92, 0x06, 0x7d, 0xab, 0x44, 0x9f, 0xfe, 0x65, 0x41, 0x4f, 0x75, 0x4a, 0xa9, 0x45, 0x52,
	0xfb, 0x26, 0x2b, 0x48, 0xee, 0xc8, 0xc8, 0x7d, 0x60, 0x9c, 0x58, 0xda, 0x50, 0xb6, 0x34, 0xc1,
	0x72, 0x04, 0xe7, 0x47, 0x20, 0xdb, 0xa0, 0x1d, 0x24, 0x4f, 0xca, 0x24, 0x1f, 0x6c, 0x1e, 0xa9,
	0x45, 0x67, 0x72, 0x3c, 0x83, 0x83, 0x75, 0xe4, 0x27, 0x9e, 0x97, 0x72, 0x72, 0x0c, 0x07, 0xd3,
	0xb2, 0x2b, 0xd3, 0xe6, 0xa6, 0x9b, 0x9e, 0x40, 0xf7, 0x22, 0x95, 0x21, 0xbd, 0x89, 0x60, 0x02,
	0xa5, 0x1a, 0x03, 0x9e, 0x79, 0x32, 0xa5, 0xad, 0x1d, 0xf4, 0x6f, 0x0b, 0xfa, 0x4f, 0x92, 0x04,
	0x23, 0x4f, 0xa5, 0x3f, 0x8e, 0x92, 0x95, 0x90, 0xba, 0x14, 0x98, 0x2e, 0x15, 0xba, 0xee, 0xaa,
	0x35, 0xa1, 0xd0, 0x4d, 0x52, 0xbc, 0xb9, 0x8a, 0xe7, 0xe3, 0xc8, 0xc3, 0x9f, 0x15, 0x99, 0xba,
	0x5b, 0xf2, 0x91, 0x23, 0xe8, 0x64, 0xf6, 0xb7, 0x72, 0x7b, 0x5d, 0x41, 0x4c, 0x17, 0x39, 0x85,
	0x26, 0x46, 0x22, 0x0d, 0x90, 0xdb, 0xfb, 0xaa, 0x01, 0x8e, 0x51, 0x8d, 0xef, 0x12, 0x8f, 0x09,
	0x7c, 0x99, 0x60, 0xca, 0x44, 0x10, 0x47, 0x6e, 0x0e, 0x95, 0x67, 0x87, 0xc8, 0x3c, 0x4c, 0x2f,
	0xe2, 0xe5, 0x32, 0x10, 0x76, 0x43, 0x9f, 0x6d, 0xfa, 0xe8, 0xaf, 0x16, 0xdc, 0x37, 0x88, 0xbc,
	0x5c, 0x09, 0xc9, 0xc4, 0x81, 0x16, 0xc7, 0xf4, 0x06, 0xd3, 0xb1, 0x97, 0xb1, 0x29, 0xec, 0x82,
	0xe5, 0x9e, 0xc1, 0xd2, 0x86, 0x26, 0xd7, 0x97, 0x53, 0x65, 0xdf, 0x72, 0x73, 0x53, 0xe6, 0xb0,
	0x64, 0x62, 0xb6, 0x40, 0x4f, 0xf3, 0xdf, 0xd7, 0x39, 0x98, 0x3e, 0x3a, 0x85, 0x83, 0x0d, 0x0e,
	0x3b, 0x4b, 0x79, 0x06, 0x5d, 0xdf, 0x50, 0xb7, 0x3a, 0xe9, 0x35, 0xe2, 0x2f, 0x81, 0xe9, 0xef,
	0x16, 0xdc, 0x77, 0x99, 0x2f, 0xc6, 0x91, 0xc0, 0x34, 0x62, 0xa1, 0x6e, 0xb2, 0x03, 0xad, 0x80,
	0x5f, 0xa9, 0x7a, 0x64, 0x3d, 0x2e, 0xec, 0x9d, 0x3c, 0x4f, 0xa0, 0x1e, 0xc6, 0x73, 0x35, 0x15,
	0x5e, 0xdf, 0x03, 0x09, 0x23, 0x1f, 0x41, 0x73, 0x89, 0x82, 0xc9, 0x6b, 0xb3, 0xbf, 0xa5, 0x61,
	0xe3, 0x9a, 0xbb, 0x39, 0x6c, 0xf4, 0x8f, 0x05, 0xb0, 0x96, 0x30, 0x39, 0x85, 0xd6, 0x57, 0x28,
	0xf4, 0xec, 0x7c, 0x73, 0x97, 0xfe, 0x9d, 0xfe, 0xa6, 0x97, 0xd6, 0xc8, 0x08, 0x5a, 0x5f, 0xaf,
	0xb2, 0x5d, 0x5b, 0xdf, 0x1d, 0x62, 0x78, 0xb2, 0x81, 0x4a, 0x6b, 0xe4, 0x0b, 0x68, 0x5f, 0x32,
	0xae, 0x10, 0x9c, 0x54, 0x5c, 0x35, 0xa7, 0xc2, 0x4f, 0x6b, 0xe4, 0x1c, 0xde, 0xc8, 0x13, 0xcd,
	0xdf, 0x82, 0x81, 0x7e, 0x59, 0x06, 0xf9, 0xcb, 0x32, 0x78, 0x2a, 0x5f, 0x96, 0xea, 0x18, 0xa3,
	0xdf, 0xf6, 0xa0, 0x2d, 0xdb, 0xa5, 0xa9, 0xeb, 0x88, 0xe6, 0x94, 0xfd, 0x2f, 0x11, 0x0d, 0x3c,
	0xad, 0x91, 0x33, 0x00, 0xdd, 0x17, 0xe9, 0x26, 0x55, 0x42, 0x29, 0x55, 0x24, 0x9b, 0x91, 0xb4,
	0x46, 0x9e, 0x41, 0x3f, 0xa7, 0x54, 0x4c, 0xc3, 0xaa, 0xc2, 0xd8, 0x55, 0xe3, 0x90, 0xd6, 0xc8,
	0x73, 0x20, 0xa5, 0x38, 0x7a, 0x2e, 0x55, 0x91, 0x71, 0x76, 0x46, 0xd2, 0x13, 0xaa, 0x36, 0xfa,
	0xa3, 0x01, 0x3d, 0x29, 0xe2, 0x49, 0x8e, 0x21, 0x57, 0xd0, 0x5b, 0xdf, 0x5e, 0x79, 0xe7, 0x1f,
	0x1a, 0x01, 0x36, 0x07, 0x94, 0x73, 0xb8, 0xfb, 0xa3, 0xbe, 0xf4, 0xb4, 0x46, 0x3e, 0x83, 0xf6,
	0x04, 0x45, 0xa6, 0xff, 0xaa, 0x14, 0xab, 0x04, 0xd4, 0x9b, 0x60, 0xe4, 0x5d, 0x22, 0x4b, 0xc5,
	0x14, 0x99, 0xb8, 0xe3, 0xf6, 0xff, 0xdb, 0xbd, 0xdd, 0x6e, 0xf2, 0x5c, 0xe5, 0x54, 0x9e, 0x58,
	0x55, 0x91, 0xcc, 0xd6, 0x6e, 0xcd, 0x39, 0x5a, 0x23, 0x9f, 0x40, 0xd3, 0x45, 0xad, 0x99, 0xbb,
	0x75, 0xe6, 0x31, 0x34, 0xd4, 0xa3, 0x77, 0xb7, 0x6d, 0xe7, 0x87, 0x3f, 0x39, 0x33, 0x8e, 0xa3,
	0xd1, 0xa9, 0xfc, 0xb5, 0x7c, 0xf5, 0x78, 0x58, 0xfa, 0x23, 0x9d, 0xde, 0x53, 0x31, 0x3e, 0xfe,
	0x37, 0x00, 0x00, 0xff, 0xff, 0x58, 0xe8, 0x5c, 0xb6, 0xa9, 0x0a, 0x00, 0x00,
}
